name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] 
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        experimental: [false]
        exclude:
          - os: windows-latest
            python-version: "3.13"
            experimental: false
        include:
          - os: windows-latest
            python-version: "3.13"
            experimental: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest-cov
        pip install -e . -r requirements.txt

    - name: Run tests
      run: |
        pytest -v --cov=src/ --cov-report html

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-python-${{ matrix.python-version }}-${{ matrix.os }}
        path: htmlcov/
